In [3]:
import numpy as np

In [4]:
voter_map = {
    0: 5,  # A
    1: 3,  # B
    2: 3,  # C
    3: 2,  # D
}

In [5]:
import itertools

voters = np.array([0, 1, 2, 3])

all_permutations = np.array(list(itertools.permutations(voters)))

In [6]:
all_permutations

quota = 9

pivotal = [0, 0, 0, 0]

for i in range(len(all_permutations)):
    sum = 0
    for j in range(4):
        sum += voter_map[all_permutations[i][j]]
        if sum >= quota:
            pivotal[all_permutations[i][j]] += 1
            break

In [7]:
pivotal / np.sum(pivotal)

array([0.5       , 0.16666667, 0.16666667, 0.16666667])

In [8]:
from winning_coalitions import Coalitions

In [9]:
w = np.array([5, 3, 3, 2])

coalitions = Coalitions(w, 8)

coalitions.relative_power

array([0.41666667, 0.25      , 0.25      , 0.08333333])

In [10]:
121 / 444 * 20

5.45045045045045

In [13]:
def hamilton_method(quota: np.ndarray, seats: int):
    seats_unrounded = quota / quota.sum() * seats
    seats_arr = np.floor(seats_unrounded)

    remainder = seats_unrounded % 1

    while seats_arr.sum() < seats:
        max_index = np.argmax(remainder)
        seats_arr[max_index] += 1
        remainder[max_index] = 0

    return seats_arr

In [14]:
quota = np.array([5.45, 4.23, 3.42, 2.16, 0.91, 1.08, 2.75])
seats = 20

hamilton_method(quota, seats)

array([6., 4., 3., 2., 1., 1., 3.])

In [22]:
def jefferson_method(pop: np.ndarray, seats: int):
    d = pop.sum() / 20

    app = np.floor(pop / d)

    while app.sum() != seats:
        if app.sum() < seats:
            d -= 1
        else:
            d += 1
        app = np.floor(pop / d)
    return app

In [24]:
pop = np.array([121, 94, 76, 48, 20, 24, 61])
seats = 20

jefferson_method(pop, seats)

array([6., 4., 3., 2., 1., 1., 3.])