In [3]:
import numpy as np

In [7]:
def f(x: np.ndarray):
    print(x)
    A = np.array(
        [
            [1, 2, 3],
            [0, 4, 3],
            [3, 5, 3],
        ]
    )
    b = np.array([1, 2, 3])

    return (A @ x + b) % 26

In [8]:
def encrypt_word(word: str, func: callable):
    res = ""
    for i in range(len(word) // 3):
        chars = word[i * 3 : i * 3 + 3]
        numeric_chars = np.array([ord(c) - 97 for c in chars])
        encrypted_numeric = func(numeric_chars)
        encrypted_chars = [chr(num_char + 97) for num_char in encrypted_numeric]
        for c in encrypted_chars:
            res += c

    return res

In [9]:
encrypt_word("banana", f)


[ 1  0 13]
[ 0 13  0]


'pptbcq'

In [11]:
def f_inv(x: np.ndarray):
    print(x)
    A_inv = np.array(
        [
            [15, 7, 4],
            [7, 4, 15],
            [8, 21, 6],
        ]
    )
    b = np.array([1, 2, 3])

    return (A_inv @ (x - b)) % 26

In [12]:
encrypt_word("xsammg", f_inv)


[23 18  0]
[12 12  6]


'orange'